
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: agprastyo
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo_list
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
